// @desc Traducciones en inglés
module.exports = {
  'homework.one': 'Task number 1',
  'homework.two': 'Homework # 2',
  'resource.not.found': 'Path invalid, bad request, the requested resource does not exist.',
  'success.hello.world.pizza': 'Pizza Delivery " Hello World ".',
  'success.pizza.response': 'Module - Pizza Delivery.',
  'success.sent.payment.confirm': 'The payment receipt sent to the users email.',
  'success.payment.applied': 'Charge generated to your credit card.',
  'success.user.created': 'The specified user created.',
  'success.user.updated': 'The specified user successfully updated.',
  'error.data.not.available': 'No data available to show or process the information.',
  'error.method.not.allowed': 'The method of the request not supported, check the documentation.',
  'error.params.missing': 'Missing parameters to continue the request.',
  'error.process.payment': 'An error occurred while processing the payment.',
  'error.sent.payment.confirm': 'The payment confirmation mail could not be sent.',
  'error.shopping.cart.add.items': 'The item could not be added to the shopping cart.',
  'error.shopping.cart.created': 'The shopping cart could not be created.',
  'error.token.delete': 'Could not find the specified token I requested to delete.',
  'error.token.expires': 'The already expired token not be extended.',
  'error.token.generated': 'Unable to generate a valid token.',
  'error.token.invalid': 'Unauthorized access: The token does not exist or is invalid.',
  'error.token.not.found': 'The specified users token could not be found.',
  'error.token.update': 'The token could not be updated.',
  'error.token.validate.login': 'The validity of the password could not be verified.',
  'error.user.created': 'The user could not be created.',
  'error.user.exists': 'The user already exists in the system.',
  'error.user.not.found': 'The user not found to process this request.',
  'error.user.password.encrypt': 'The user could not be generated, error with the password.',
  'error.user.deleted': 'The specified user could not be deleted.',
  'error.user.updated': 'The user could not be updated.',
  'error.data.not.added.to.order': 'The item could not be added to the purchase order.',
  'error.item.not.exists': 'The item cannot be added to the shopping cart.',
  'error.sent.sms': 'The notification could not be sent.',
  'success.sent.sms': 'The notification has been sent.',
  'account.create.page.title': 'Create a user account.',
  'account.create.page.description': 'Register to use the service.',
  'account.create.title': 'Register your account.',
  'account.edit.page.title': 'Edit account settings.',
  'account.edit.title': 'Account settings.',
  'account.delete.page.title': 'Danger zone.',
  'account.delete.title': 'The account has been deleted.',
  'session.create.page.title': 'Login to your account',
  'session.create.page.description': 'Please enter the access data, to start session.',
  'session.create.title': 'Gateway to the system',
  'session.delete.page.title': 'Logout',
  'session.delete.page.description': 'The session has ended.',
  'session.delete.title': 'Thanks for using the system',
  'check.list.page.title': 'Dashboard',
  'check.list.title': 'Web site checkers',
  'check.create.page.title': 'Create a new check',
  'check.create.title': 'Web site check',
  'check.edit.page.title': 'Check details',
  'check.edit.title': 'Checks edit',
  'check.delete.page.title': 'Logout',
  'check.delete.page.description': 'The session has ended.',
  'check.delete.title': 'Thank you for using the system',
  'pages.index.page.title': 'Uptime monitoring - Devops made simple',
  'pages.index.page.description': 'Check the availability of all your websites, we will send you a message if any of them have errors',
  'pages.index.title': 'HTTP / HTTPS Website monitoring',
  'error.user.forbidden.permissions': 'You do not have permissions to continue.',
  'error.terms.and.policy': 'You must accept the terms and conditions of the service',
}
