// @desc Traducciones en inglés
module.exports = {
  'homework.one': 'Task number 1',
  'homework.two': 'Homework # 2',
  'resource.not.found': 'Path invalid, bad request, the requested resource does not exist.',
  'success.hello.world.pizza': 'Pizza Delivery " Hello World ".',
  'success.pizza.response': 'Module - Pizza Delivery.',
  'success.sent.payment.confirm': 'The payment receipt sent to the users email.',
  'success.payment.applied': 'Charge generated to your credit card.',
  'success.user.created': 'The specified user created.',
  'success.user.updated': 'The specified user successfully updated.',
  'error.data.not.available': 'No data available to show or process the information.',
  'error.method.not.allowed': 'The method of the request not supported, check the documentation.',
  'error.params.missing': 'Missing parameters to continue the request.',
  'error.process.payment': 'An error occurred while processing the payment.',
  'error.sent.payment.confirm': 'The payment confirmation mail could not be sent.',
  'error.shopping.cart.add.items': 'The item could not be added to the shopping cart.',
  'error.shopping.cart.created': 'The shopping cart could not be created.',
  'error.token.delete': 'Could not find the specified token I requested to delete.',
  'error.token.expires': 'The already expired token not be extended.',
  'error.token.generated': 'Unable to generate a valid token.',
  'error.token.invalid': 'Unauthorized access: The token does not exist or is invalid.',
  'error.token.not.found': 'The specified users token could not be found.',
  'error.token.update': 'The token could not be updated.',
  'error.token.validate.login': 'The validity of the password could not be verified.',
  'error.user.created': 'The user could not be created.',
  'error.user.exists': 'The user already exists in the system.',
  'error.user.not.found': 'The user not found to process this request.',
  'error.user.password.encrypt': 'The user could not be generated, error with the password.',
  'error.user.deleted': 'The specified user could not be deleted.',
  'error.user.updated': 'The user could not be updated.',
}
