// @desc Traducciones en español
module.exports = {
  'homework.one': 'Tarea número 1',
  'homework.two': 'Homework #2',
  'resource.not.found': 'Ruta invalida, el recurso solicitado no existe.',
  'success.hello.world.pizza': 'Entrega de Pizza "Hola Mundo".',
  'success.ping': 'Aplicación en línea.',
  'success.pizza.response': 'Modulo - Entrega de Pizza.',
  'success.sent.payment.confirm': 'Se envió el comprobante de pago al correo electrónico del usuario.',
  'success.payment.applied': 'Cargo generado a su tarjeta de crédito.',
  'success.user.created': 'Se ha creado el usuario especificado.',
  'success.user.updated': 'Sé actualizo con éxito el usuario especificado.',
  'success.record.updated': 'El registro sé actualizo con éxito',
  'error.data.not.available': 'No hay datos disponibles para mostrar o procesar la información.',
  'error.method.not.allowed': 'El método de la solicitud no está soportado, revise la documentación.',
  'error.params.missing': 'Faltan parámetros para continuar con la solicitud.',
  'error.process.payment': 'Se ha generado un error al procesar el pago.',
  'error.sent.payment.confirm': 'No se pudo enviar el correo de confirmación de pago.',
  'error.shopping.cart.add.items': 'No se pudo agregar el artículo al carrito de compras.',
  'error.shopping.cart.created': 'No se pudo crear el carrito de compras.',
  'error.token.delete': 'No se pudo encontrar el token especificado que solicito para eliminar.',
  'error.token.expires': 'El token ya caduco, no puede ser extendido.',
  'error.token.generated': 'No se pudo generar un token valido.',
  'error.token.invalid': 'Acceso no autorizado: El token no existe o es invalido.',
  'error.token.not.found': 'No se pudo encontrar el token del usuario especificado.',
  'error.token.update': 'No se pudo actualizar el token.',
  'error.token.validate.login': 'No se pudo verificar la validez del password.',
  'error.user.check.deleted': 'Algunos registros checks no se pudieron eliminar.',
  'error.user.created': 'No se pudo crear el usuario.',
  'error.user.exists': 'El usuario ya existe en el sistema.',
  'error.user.not.found': 'No se encontró el usuario para procesar esta solicitud.',
  'error.user.password.encrypt': 'No se pudo generar el usuario, error con la contraseña.',
  'error.user.deleted': 'No se pudo eliminar el usuario especificado.',
  'error.user.updated': 'No se pudo actualizar él usuario.',
  'error.user.max.checks': 'Error el usuario ya tiene el número máximo de checadas.',
  'error.user.update.checks': 'Error no se pudo actualizar el usuario con su checada.',
  'error.checks.created': 'Error no se pudo crear el registro para las checadas.',
  'error.check.missing.fields': 'Error no hay datos por actualizar.',
  'error.check.user.found': 'No se pudo encontrar el usuario que creo el registro del check.',
  'error.record.delete': 'Error no se ha podido eliminar el registro indicado.',
  'error.record.updated': 'Error al actualizar la información del registro.',
  'error.data.not.added.to.order': 'No se pudo agregar el artículo a la orden de compra.',
  'error.item.not.exists': 'El artículo no se puede agregar al carrito de compras.',
  'error.sent.sms': 'No se pudo realizar el envío de la notificación.',
  'success.sent.sms': 'Se ha enviado la notificación.',
}
